#!/usr/bin/env python3
"""
rl_finetune.py — REINFORCE self-play fine-tuning for the CoT student (#3).

The supervised pipeline can never exceed its teacher's labels. This script
closes that gap with policy-gradient RL:

  1. Sample deals. The STUDENT plays North+South; the symbolic DSL system
     plays East+West (greedy: pass preferred, else lowest modeled bid).
  2. Each student decision is generated by SAMPLING from the policy
     (temperature > 0) starting from its state prefix. If the decoded bid
     is illegal or unparseable, the segment falls back to the teacher and
     contributes NO gradient (safe-guarded exploration).
  3. When the auction terminates, the contract is scored with the native
     Double Dummy Solver from North/South's perspective and converted to
     IMPs (score_to_imp as utility proxy).
  4. REINFORCE update: loss_segment = -advantage * sum_t log pi(tok_t),
     where advantage = (reward - batch_mean) / batch_std shares the
     terminal outcome across all of that board's student segments.

The incumbent checkpoint is NEVER modified — output goes to --out
(default data/cot_model/ckpt_rl.pt); A/B it before promoting.

Usage:
  PYTHONPATH=.. python3 rl_finetune.py --boards 16 [--epochs 2]
      [--temp 0.7] [--lr 2e-5] [--seed 42]
"""

import argparse
import json
import math
import os
import statistics

import torch

from bid.models import Seat, CallType
from bid.pidm import PIDMEngine
from eval_vs_dds import build_deals, load_decision_net_dsl, SYSTEM_DIR
from mine_disagreements import StudentPolicy
from trace_factory import hand_str


def ew_greedy_call(net, hand, history, seat, dealer, vuln):
    """Deterministic EW behavior: PASS when legal, else lowest ranked bid."""
    acts = net.actions(hand, history, seat, dealer, vuln)
    if CallType.PASS in {a.type for a in acts} and \
            any(a.type == CallType.PASS for a in acts):
        return next(a for a in acts if a.type == CallType.PASS)
    bids = sorted((a for a in acts if a.type == CallType.BID),
                  key=lambda c: (c.level, c.strain.value))
    return bids[0] if bids else sorted(acts, key=lambda c: c.type.name)[0]


def generate_segment(student, prefix_ids, legal_strs, temp,
                     max_new=40):
    """
    Sample one reasoning+bid continuation.
    Returns dict(bid, token_logps(list[float]), n_tokens, illegal(bool)).
    """
    V = student.vocab
    sep_id = V["<sep>"]
    eot_id = V["<eot>"]
    pad_id = V["<pad>"]
    ids = [i for i in prefix_ids if i != pad_id]
    # ensure we start generating right after <sep>
    if sep_id not in ids:
        ids.append(sep_id)
    gen_ids, logps = [], []
    with torch.no_grad():
        for _ in range(max_new):
            x = torch.tensor([ids[-student.block:]]).to(student.dev)
            logits, _ = student.model(x)
            lx = logits[0, -1]
            if temp > 0:
                probs = torch.softmax(lx / temp, dim=-1)
                nxt = int(torch.multinomial(probs, 1))
            else:
                nxt = int(torch.argmax(lx))
            logp = float(torch.log_softmax(lx, dim=-1)[nxt])
            if nxt in (eot_id, pad_id, sep_id):
                break
            ids.append(nxt)
            gen_ids.append(nxt)
            logps.append(logp)
    text = " ".join(student.inv[i] for i in gen_ids)
    parts = text.split()
    bid = None
    if "BID" in parts:
        k = len(parts) - parts[::-1].index("BID")
        tail = " ".join(parts[k:])
        bid = tail or None
    illegal = bid is None or bid not in legal_strs
    return {"bid": bid, "token_ids": gen_ids, "token_logps": logps,
            "illegal": illegal}


def play_board(student, net, deal, base_engine, temp, max_calls=24):
    """
    Plays one full auction (student = N/S).
    Returns (segments, reward_ns_imps). Only LEGAL student decisions are
    kept as trainable segments; illegal ones fall back to the teacher and
    are marked teacher_guided=True (no gradient).
    """
    from bid.sampling import PartialState
    from bid.scoring import (Vulnerability, calculate_contract_score,
                             score_to_imp)
    from bid.dds import DDSolver

    models = {s: net for s in Seat}
    history, curr, n = [], deal.dealer, 0
    segments = []
    while len(history) < max_calls:
        ps = PartialState(curr, deal.hands[curr], history,
                          deal.dealer, deal.vuln)
        if ps.is_auction_over():
            break
        legal_acts = net.actions(deal.hands[curr], history, curr,
                                 deal.dealer, deal.vuln)
        if curr in (Seat.NORTH, Seat.SOUTH):
            prefix = student.prefix_ids(
                deal.dealer.name, deal.vuln, curr.name, n,
                [str(c) for c in history],
                hand_str(deal.hands[curr]))
            legal = {str(c) for c in legal_acts}
            seg = generate_segment(student, prefix, legal, temp)
            seg["prefix"] = prefix
            call = next((c for c in legal_acts
                         if str(c) == seg["bid"]), None)
            if call is not None:
                segments.append(seg)
            else:
                seg["teacher_guided"] = True   # no gradient contribution
                call = base_engine.decide(ps, models)[0]
        else:
            call = ew_greedy_call(net, deal.hands[curr], history, curr,
                                  deal.dealer, deal.vuln)
        history.append(call)
        curr = Seat((curr.value + 1) % 4)
        n += 1

    # ---- terminal reward (NS perspective) -------------------------------
    end_ps = PartialState(Seat.NORTH, deal.hands[Seat.NORTH], history,
                          deal.dealer, deal.vuln)
    contract = end_ps.get_contract()
    if contract is None:
        return segments, 0.0
    level, strain, declarer, doubled = contract
    from bid.dds import DDSolver
    tricks = DDSolver.get_tricks(deal, strain, declarer)
    raw = calculate_contract_score(
        level=level, strain=strain, doubled=doubled,
        is_vulnerable=Vulnerability.is_vulnerable(deal.vuln, declarer),
        tricks_taken=tricks)
    ns_raw = float(raw) if declarer in (Seat.NORTH, Seat.SOUTH) \
        else -float(raw)
    return segments, float(score_to_imp(int(ns_raw)))


def reinforce_update(model, opt, episodes, dev, clip=1.0):
    """
    One pass of REINFORCE. episodes: (prefix_ids, token_ids, advantage).
    Recomputes token log-probs WITH gradient; loss_seg = -A * sum logp
    normalized by segment length.
    """
    tot_loss = 0.0
    for prefix, token_ids, adv in episodes:
        ids = list(prefix)
        lp_sum = torch.zeros((), dtype=torch.float32, device=dev)
        with torch.enable_grad():
            for tid in token_ids:
                x = torch.tensor([ids[-model.block_size:]]).to(dev)
                logits, _ = model(x)
                lsm = torch.log_softmax(logits[0, -1], dim=-1)
                lp_sum = lp_sum + lsm[tid]
                ids.append(tid)
            loss_seg = -(adv * lp_sum) / max(1, len(token_ids))
        opt.zero_grad(set_to_none=True)
        loss_seg.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), clip)
        opt.step()
        tot_loss += float(loss_seg)
    return tot_loss / max(1, len(episodes))


def main():
    ap = argparse.ArgumentParser(description="REINFORCE fine-tuning")
    ap.add_argument("--boards", type=int, default=16)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--ckpt", default="data/cot_model/ckpt.pt")
    ap.add_argument("--out", default="data/cot_model/ckpt_rl.pt")
    ap.add_argument("--dsl", default=os.path.join(SYSTEM_DIR,
                                                  "improved_system.dsl"))
    ap.add_argument("--epochs", type=int, default=2)
    ap.add_argument("--temp", type=float, default=0.7)
    ap.add_argument("--lr", type=float, default=2e-5)
    args = ap.parse_args()

    student = StudentPolicy(args.ckpt)
    net = load_decision_net_dsl(args.dsl)
    base_engine = PIDMEngine()          # only for illegal-fallback moves
    deals = build_deals(args.boards, seed=args.seed,
                        include_stratified=False)

    all_segments, rewards = [], []
    guided_n = 0
    half = max(1, len(deals) // 2)
    r_first, r_second = [], []

    for b_idx, deal in enumerate(deals, 1):
        segs, r = play_board(student, net, deal, base_engine, args.temp)
        rewards.append(r)
        (r_first if b_idx <= half else r_second).append(r)
        guided_n += sum(1 for s in segs if s.get("teacher_guided"))
        for s in segs:
            if not s.get("teacher_guided"):
                all_segments.append((s["prefix"], s["token_ids"], r))
        if b_idx % 4 == 0 or b_idx == len(deals):
            print(f"  board {b_idx}/{len(deals)} | reward {r:+.0f} | "
                  f"segments {len(all_segments)}", flush=True)

    mean_r = statistics.fmean(rewards) if rewards else 0.0
    sd_r = statistics.pstdev(rewards) if len(rewards) > 1 else 1.0
    print(f"\ncollected {len(all_segments)} trainable segments "
          f"from {len(deals)} boards | teacher-guided {guided_n}")
    print(f"  mean NS IMPs/board: {mean_r:+.2f} "
          f"(first half {statistics.fmean(r_first):+.2f} vs "
          f"second {statistics.fmean(r_second):+.2f})")

    episodes = [(pfx, tids, (r - mean_r) / (sd_r if sd_r > 1e-6 else 1.0))
                for pfx, tids, r in all_segments]

    opt = torch.optim.AdamW(student.model.parameters(), lr=args.lr)
    for ep in range(args.epochs):
        avg = reinforce_update(student.model, opt, episodes, student.dev)
        print(f"  rl epoch {ep}: policy-loss {avg:+.4f}")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    torch.save(student.model.state_dict(), args.out)
    vocab_src = args.ckpt + ".vocab.json"
    if os.path.exists(vocab_src):
        import shutil
        shutil.copy(vocab_src, args.out + ".vocab.json")
    print(f"saved RL checkpoint -> {args.out}")


if __name__ == "__main__":
    main()

