# 1NT - 3M Splinter Responses
1NT - 3H:
  CONVENTION: 1NT_3H_Splinter
  FORCING: GAME_FORCING
  HCP: 10-14
  LEN H: 0-1
  SHAPE: UNBALANCED

1NT - 3S:
  CONVENTION: 1NT_3S_Splinter
  FORCING: GAME_FORCING
  HCP: 10-14
  LEN S: 0-1
  SHAPE: UNBALANCED
