# Splinters (4+ Trump Support, Shortness 0-1, Game Forcing)

# 1H / 1S Opening Splinters
1H - 3S:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10-14
  LEN H: 4+
  LEN S: 0-1
  SHAPE: UNBALANCED

1H - 4C:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10-14
  LEN H: 4+
  LEN C: 0-1
  SHAPE: UNBALANCED

1H - 4D:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10-14
  LEN H: 4+
  LEN D: 0-1
  SHAPE: UNBALANCED

1S - 4C:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10-14
  LEN S: 4+
  LEN C: 0-1
  SHAPE: UNBALANCED

1S - 4D:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10-14
  LEN S: 4+
  LEN D: 0-1
  SHAPE: UNBALANCED

1S - 4H:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10-14
  LEN S: 4+
  LEN H: 0-1
  SHAPE: UNBALANCED

# Splinters after Stayman (1NT - 2C - 2H / 2S)
1NT - 2C - 2H - 4C:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10+
  LEN H: 4+
  LEN C: 0-1
  SHAPE: UNBALANCED

1NT - 2C - 2H - 4D:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10+
  LEN H: 4+
  LEN D: 0-1
  SHAPE: UNBALANCED

1NT - 2C - 2S - 4C:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10+
  LEN S: 4+
  LEN C: 0-1
  SHAPE: UNBALANCED

1NT - 2C - 2S - 4D:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10+
  LEN S: 4+
  LEN D: 0-1
  SHAPE: UNBALANCED

1NT - 2C - 2S - 4H:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10+
  LEN S: 4+
  LEN H: 0-1
  SHAPE: UNBALANCED

# Splinters after Transfer to Hearts (1NT - 2D - 2H)
1NT - 2D - 2H - 3S:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10+
  LEN H: 6+
  LEN S: 0-1
  SHAPE: UNBALANCED

1NT - 2D - 2H - 4C:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10+
  LEN H: 6+
  LEN C: 0-1
  SHAPE: UNBALANCED

1NT - 2D - 2H - 4D:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10+
  LEN H: 6+
  LEN D: 0-1
  SHAPE: UNBALANCED

# Splinters after Transfer to Spades (1NT - 2H - 2S)
1NT - 2H - 2S - 4C:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10+
  LEN S: 6+
  LEN C: 0-1
  SHAPE: UNBALANCED

1NT - 2H - 2S - 4D:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10+
  LEN S: 6+
  LEN D: 0-1
  SHAPE: UNBALANCED

1NT - 2H - 2S - 4H:
  CONVENTION: Splinter
  FORCING: GAME_FORCING
  PRIORITY_BONUS: 15
  HCP: 10+
  LEN S: 6+
  LEN H: 0-1
  SHAPE: UNBALANCED
